'use strict';
const G = window.TroyCoop;
const SAVE_KEY = 'ilia-cooperativo-v2';
let state = null, selected = 'aquiles', pending = null, confirmation = null, saved = null, storageOK = true;
const app = document.getElementById('app');
const esc = value => String(value).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
try { const raw = localStorage.getItem(SAVE_KEY); if(raw){const parsed=JSON.parse(raw);if(G.validSave(parsed))saved=parsed;} } catch(e){storageOK=false;}
function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));saved=state;}catch(e){storageOK=false;}}
let noticeTimer;
function notice(text){document.getElementById('notice').textContent=text;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>document.getElementById('notice').textContent='',6000);}
function button(label,command,extra='',disabled=false,cls='action'){return `<button class="${cls}" data-command="${command}" ${extra} ${disabled?'disabled':''}>${label}</button>`;}
function briefing(){
  app.innerHTML=`<section class="briefing"><p class="eyebrow">MISSÃO 01 / COOPERATIVO LOCAL</p><h1>Salvem os navios.</h1><p class="lead">Troia lançou uma ofensiva contra a praia. Preparem a retirada e levem os três heróis de volta à frota antes que os navios sejam incendiados.</p><div class="brief-grid"><div class="box"><h3>Um objetivo em comum</h3><p>Encontrem mantimentos em A1/A2, cordas em B2/B4 e a tocha em C2/C3. Há um artefato inteiro escondido em um dos dois pontos de cada terreno. Depois, reúnam todos em N1 e partam com a frota.</p><p><b>Vocês têm até ${G.MAX_ROUNDS} rodadas.</b> A frota suporta apenas 2 danos; o terceiro encerra a missão.</p></div><div class="box"><h3>Escolham juntos. Ajam juntos.</h3><p>Cada herói tem 2 ações por rodada. Movam, ataquem, cumpram tarefas ou usem habilidades. Ao encerrar a rodada, os troianos respondem automaticamente.</p><p>1–3 pessoas no mesmo aparelho. No solo, você controla os três heróis. Sem salas online nesta versão.</p></div></div><div class="brief-heroes">${G.HEROES.map(h=>`<div class="brief-hero"><b>${h.name}</b><small>${h.role} · 3 habilidades</small></div>`).join('')}</div><div class="actions-row">${saved&&!saved.result?button('Continuar missão · rodada '+saved.round,'continue','',false,'button'):''}${button(saved&&!saved.result?'Começar outra missão':'Começar missão','start','',false,'button '+(saved&&!saved.result?'secondary':''))}</div>${confirmation==='new'?newConfirm():''}<p class="saved-note">${storageOK?'Progresso salvo automaticamente neste navegador.':'Armazenamento indisponível: mantenha esta página aberta para preservar a partida.'} Os esconderijos são sorteados uma vez por missão. Partidas do mapa antigo ficam preservadas separadamente neste navegador.</p></section>`;
}
function newConfirm(){return `<div class="confirm-row"><p>Começar outra missão substitui o progresso salvo neste navegador.</p><div class="actions-row">${button('Começar do início','new-confirm','',false,'quiet')}${button('Cancelar','cancel','',false,'quiet')}</div></div>`;}
function mapHTML(){return puzzleMap(state,selected);}
function targets(action,h){
  if(action==='move')return G.ZONES[h.zone].links.map(z=>[z,G.ZONES[z].name]);
  if(action==='attack')return state.enemies.filter(e=>e.zone===h.zone).map(e=>[e.id,`Grupo ${e.id.slice(1)} · ${e.hp}♥`]);
  if(action==='rescue')return state.heroes.filter(a=>a.hp===0&&a.zone===h.zone).map(a=>[a.id,G.HEROES.find(d=>d.id===a.id).name]);
  if(action.startsWith('card:')){
    const c=G.HEROES.find(d=>d.id===h.id).cards[Number(action.slice(5))];
    if(['attack','ranged','charge'].includes(c.type))return state.enemies.filter(e=>c.type==='charge'?G.distance(h.zone,e.zone)===1:G.distance(h.zone,e.zone)<=(c.type==='ranged'?1:0)).map(e=>[e.id,`Grupo ${e.id.slice(1)} · ${G.ZONES[e.zone].name} · ${e.hp}♥`]);
    if(c.type==='healAlly')return state.heroes.filter(a=>a.id!==h.id&&a.zone===h.zone&&a.hp<6).map(a=>[a.id,G.HEROES.find(d=>d.id===a.id).name]);
    if(c.type==='guide')return state.heroes.filter(a=>a.id!==h.id&&a.hp>0&&a.zone===h.zone).flatMap(a=>G.ZONES[h.zone].links.map(z=>[a.id+':'+z,G.HEROES.find(d=>d.id===a.id).name+' → '+G.ZONES[z].name]));
    if(c.type==='sprint')return Object.keys(G.ZONES).filter(z=>z!==h.zone&&G.distance(h.zone,z)<=2).map(z=>[z,G.ZONES[z].name]);
  }return null;
}
function commandHTML(){
  const h=state.heroes.find(x=>x.id===selected),d=G.HEROES.find(x=>x.id===selected),disabled=!!state.result||h.hp===0||h.ap===0,foes=state.enemies.some(e=>e.zone===h.zone);
  const hasInteraction=(G.ZONES[h.zone].search&&!state.tasks.includes(G.ZONES[h.zone].terrain)&&!state.searched.includes(h.zone))||(h.zone==='N1'&&state.tasks.length===3&&state.heroes.every(a=>a.hp>0&&a.zone==='N1'));
  return `<aside class="command"><div class="hero-tabs" aria-label="Escolher herói">${state.heroes.map(a=>button(`${G.HEROES.find(d=>d.id===a.id).name}<small>${a.hp===0?'Caído':a.ap+'/2 ações · '+a.hp+'♥'}</small>`,'hero',`data-id="${a.id}" aria-pressed="${a.id===selected}"`,false,'hero-tab '+(a.id===selected?'active':''))).join('')}</div><div class="box"><div class="hero-heading"><h2>${d.name}</h2><span>${h.hp}/6 ♥</span></div><p class="context">${d.role} · ${G.ZONES[h.zone].name} · <b>${h.ap} ação(ões)</b>${h.hp===0?' · Precisa ser socorrido':''}</p><div class="action-grid">${button('Mover<small>1 área conectada</small>','action','data-action="move"',disabled)}${button('Atacar<small>2 de dano nesta área</small>','action','data-action="attack"',disabled||!foes)}${button(`${h.zone==='N1'?'Partir com a frota':'Investigar'}<small>${h.zone==='N1'?'Todos reunidos em N1':'Ponto de busca · 1 ação'}</small>`,'action','data-action="interact"',disabled||foes||!hasInteraction)}${button('Recuperar<small>Habilidades + 1 de vida</small>','action','data-action="rest"',disabled||foes||(!h.used.length&&h.hp===6))}${state.heroes.some(a=>a.hp===0&&a.zone===h.zone)?button('Socorrer<small>Levante um aliado com 2 de vida</small>','action','data-action="rescue"',disabled):''}</div>${pending?`<div class="target-box"><p>Escolha o alvo ou destino. Custo: 1 ação.</p><div class="target-options">${(targets(pending,h)||[]).map(([id,label])=>button(esc(label),'target',`data-target="${esc(id)}"`,false,'')).join('')}${button('Cancelar','cancel','',false,'quiet')}</div></div>`:''}<p class="ability-title">HABILIDADES · CADA USO CUSTA 1 AÇÃO</p>${d.cards.map((c,i)=>{const t=targets('card:'+i,h);const unavailable=(t&&t.length===0)||(c.type==='heal'&&h.hp===6);return button(`<strong>${c.name}${h.used.includes(i)?' · esgotada':''}</strong><small>${c.text}</small>`,'action',`data-action="card:${i}"`,disabled||h.used.includes(i)||unavailable,'card '+(pending==='card:'+i?'selected':''));}).join('')}<p class="saved-note">Recuperar deixa as três habilidades prontas novamente.</p></div>${!state.result?button('Encerrar rodada → Troia responde','end','',false,'button turn-end'):''}${confirmation==='end'?`<div class="confirm-row"><p>Ainda há ${state.heroes.reduce((n,a)=>n+(a.hp>0?a.ap:0),0)} ações disponíveis. Encerrar descarta essas ações.</p><div class="actions-row">${button('Encerrar mesmo assim','end-confirm','',false,'quiet')}${button('Continuar jogando','cancel','',false,'quiet')}</div></div>`:''}<p class="saved-note">${storageOK?'Partida salva neste navegador.':'Não foi possível salvar. Mantenha esta página aberta.'}</p></aside>`;
}
function render(){
  if(!state){briefing();return;}
  app.innerHTML=`<div class="mission-header"><div><p class="eyebrow">MISSÃO 01 / EM EQUIPE</p><h1>Salvem os navios</h1><p>${state.tasks.length===3?'Artefatos reunidos. Levem todos os heróis a N1 e partam com a frota.':'Procurem em A1/A2, B2/B4 e C2/C3. Reúnam os três artefatos e retornem a N1.'}</p></div><div class="metrics"><div class="metric">RODADA<strong>${state.round} / ${G.MAX_ROUNDS}</strong></div><div class="metric">ARTEFATOS<strong>${state.tasks.length} / 3</strong></div><div class="metric">DANOS À FROTA<strong>${state.shipDamage} / 3</strong></div></div></div>${state.result?`<section class="result ${state.result}" role="status"><p class="eyebrow">MISSÃO ENCERRADA</p><h2>${state.result==='victory'?'A frota está a salvo.':'Troia impediu a retirada.'}</h2><p>${esc(state.reason)}</p><div class="actions-row">${button('Jogar novamente','new-confirm','',false,'button')}<a class="button secondary" href="../index.html">Escolher outro modo</a></div></section>`:''}<div class="game-layout"><div>${mapHTML()}<section class="box threats"><h3>Próxima resposta de Troia</h3>${state.result?'<p>A missão terminou.</p>':state.enemies.map(e=>`<div class="threat-row"><b>Grupo ${e.id.slice(1)} · ${G.ZONES[e.zone].name}</b><span>${G.intent(e,state)}</span></div>`).join('')||'<p>Nenhum grupo em campo.</p>'}${!state.result?`<div class="reinforcements">${state.round===G.MAX_ROUNDS?'Última rodada: partam antes de encerrá-la.':(G.WAVES[state.round+1]?.length?'Depois da resposta: reforços em '+G.WAVES[state.round+1].map(z=>G.ZONES[z].name).join(' e ')+'.':'Depois da resposta: sem novos reforços.')}</div>`:''}</section><details class="log"><summary>Registro da missão · ${state.log.length} acontecimentos</summary><ol>${state.log.map(msg=>`<li>${esc(msg)}</li>`).join('')}</ol></details></div>${commandHTML()}</div><footer><a href="../index.html">← Escolher modo</a> · Cooperativo local · ${button('Recomeçar missão','start','',false,'quiet')}</footer>${confirmation==='new'?newConfirm():''}`;
}
function perform(action,target){const result=G.act(state,selected,action,target);if(!result.ok){notice(result.error);return;}state=result.state;pending=null;confirmation=null;persist();render();if(action==='interact')notice(state.log[0]);if(state.result){notice(state.reason);window.scrollTo({top:0,behavior:'smooth'});}}
function endRound(){state=G.trojanTurn(state);pending=null;confirmation=null;persist();render();notice(state.result?state.reason:'Troia respondeu. Rodada '+state.round+' iniciada.');if(state.result)window.scrollTo({top:0,behavior:'smooth'});}
app.addEventListener('click',event=>{
  const b=event.target.closest('button[data-command]');if(!b||b.disabled)return;
  const c=b.dataset.command;
  if(c==='start'){if((state&&!state.result)||(saved&&!saved.result)){confirmation='new';render();}else{state=G.newGame();selected='aquiles';persist();render();}}
  else if(c==='new-confirm'){state=G.newGame();selected='aquiles';pending=null;confirmation=null;persist();render();window.scrollTo(0,0);}
  else if(c==='continue'){state=JSON.parse(JSON.stringify(saved));render();}
  else if(c==='hero'){selected=b.dataset.id;pending=null;confirmation=null;render();}
  else if(c==='cancel'){pending=null;confirmation=null;render();}
  else if(c==='action'){const a=b.dataset.action,h=state.heroes.find(x=>x.id===selected),t=targets(a,h);confirmation=null;if(t){if(!t.length){notice('Não há um alvo válido para esta ação.');return;}pending=a;render();}else perform(a);}
  else if(c==='target'){if(pending)perform(pending,b.dataset.target);}
  else if(c==='end'){if(state.heroes.some(h=>h.hp>0&&h.ap>0)){confirmation='end';pending=null;render();}else endRound();}
  else if(c==='end-confirm')endRound();
});
const rules=document.getElementById('rules');document.getElementById('rules-button').addEventListener('click',()=>rules.showModal());document.getElementById('close-rules').addEventListener('click',()=>rules.close());rules.addEventListener('click',e=>{if(e.target===rules){const r=rules.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)rules.close();}});
render();
