(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./muralhas.js'));else root.TroyDefense=factory(root.TroyWalls);})(typeof globalThis!=='undefined'?globalThis:this,function(W){
 'use strict';
 const VERSION=6,MAX_ROUNDS=8,FOOD_LIMIT=2,H=W.HEROES,T=W.TROOPS,clone=s=>JSON.parse(JSON.stringify(s));
 const MISSION_TWO_ZONES=['A1','A2','N1','N2','N3','N4','N5','P1','P2','P3','P4','P5','P6','P7','C1','C2','B1','B5','M1','M2','M4','M5'];
 function log(s,msg){s.log.unshift(msg);s.log=s.log.slice(0,100);}
 function spawn(s,zone,type){const e=T.create('e'+s.nextEnemy++,zone,type);s.enemies.push(e);if(T.types[type].hero)s.commanders[type]='active';return e;}
 function regularCount(s){return Math.max(1,s.heroes.length-2);}
 function newGame(options={}){
  const ids=options.heroes||['odisseu','agamemnon','aquiles'],owners=options.owners||ids.map(()=>1),continuing=options.campaign&&ids.length>0;
  const s=continuing?W.newGame({players:1,heroes:['odisseu','agamemnon','aquiles'],owners:[1,1,1]}):W.newGame(options);
  if(continuing){
   if(ids.length>5||new Set(ids).size!==ids.length||ids.some(id=>!H.some(h=>h.id===id))||owners.length!==ids.length)throw Error('A equipe sobrevivente da campanha é inválida.');
   s.players=Math.max(1,Math.min(5,options.players||new Set(owners).size||1));
   s.playerNames=Array.from({length:s.players},(_,i)=>String(options.playerNames?.[i]||`Jogador ${i+1}`).trim().slice(0,30));
   s.heroes=ids.map((id,i)=>({...H.create(id,options.levels?.[id]??1),owner:Number.isInteger(owners[i])&&owners[i]>=1&&owners[i]<=s.players?owners[i]:1,zone:'A1',cargo:false,food:Math.min(FOOD_LIMIT,Math.max(0,options.food?.[id]??options.campaign?.team?.food?.[id]??FOOD_LIMIT))}));
  }
  s.campFood=Math.max(0,options.resources?.food??options.campaign?.resources?.food??s.campFood??0);
  s.version=VERSION;s.mission='defesa';s.campDamage=0;s.defended=0;s.gateAssaulted=true;s.retreatDeadline=null;s.ambush=false;s.revealedZones=[...MISSION_TWO_ZONES];s.explorations={P3:{type:'reveal',amount:1,resolved:false},C1:{type:'evolution-map',amount:1,resolved:false}};s.evolutionChoices=[];s.enemies=[];s.nextEnemy=1;s.log=[];s.commanders={heitor:'unseen',paris:'unseen',eneias:options.campaign?.commanders?.eneias==='dead'?'dead':'unseen',sarpedon:options.campaign?.commanders?.sarpedon==='dead'?'dead':'unseen'};s.heroes.forEach(h=>h.weapon=true);s.weaponStock=0;
  const starts=['M1','M2'];for(let i=0;i<regularCount(s);i++)spawn(s,starts[i%starts.length],'lanceiro');
  log(s,'A ofensiva saiu pelos portões M1 e M2. Segurem a linha e explorem P3 e C1 antes da oitava rodada.');return s;
 }
 function waveEntries(s,round){const bonus=Math.max(0,s.heroes.length-3),entries=[];
  if(round===2){for(let i=0;i<1+bonus;i++)entries.push([i%2?'M2':'M1','explorador']);if(s.commanders.eneias!=='dead')entries.push(['M2','eneias']);}
  if(round===3){entries.push(['M1','heitor']);for(let i=0;i<bonus;i++)entries.push(['M2','lanceiro']);}
  if(round===4){entries.push(['M2','paris']);if(s.commanders.sarpedon!=='dead')entries.push(['M1','sarpedon']);for(let i=0;i<bonus;i++)entries.push(['M2','arqueiro']);}
  if(round===5)for(let i=0;i<1+bonus;i++)entries.push([i%2?'M2':'M1','lanceiro']);
  if(round===6){entries.push(['M1','guarda']);for(let i=0;i<bonus;i++)entries.push(['M2','arqueiro']);}
  if(round===7){entries.push(['M2','arqueiro']);for(let i=0;i<bonus;i++)entries.push(['M1','lanceiro']);}
  if(round===8){entries.push(['M1','lanceiro']);for(let i=0;i<bonus;i++)entries.push(['M2','arqueiro']);}
  return entries;
 }
 function interaction(s,h){if(s.explorations[h.zone]&&!s.explorations[h.zone].resolved)return {label:'Explorar',detail:h.zone==='P3'?'Revelar M3':'Completar o mapa e obter evolução',available:true};if(h.zone==='A1'&&s.campDamage>0&&(h.food>0||s.campFood>0))return {label:'Explorar',detail:'Reparar A1 · 1 comida',available:true};if(h.zone==='A1'&&h.food<FOOD_LIMIT&&s.campFood>0)return {label:'Explorar',detail:'Repor alimento no acampamento',available:true};return {label:'Explorar',detail:'Nenhuma interação disponível',available:false};}
 function finish(s,result,reason){s.result=result;s.phase='end';s.reason=reason;if(result==='victory')s.outcome={completed:'defesa',next:'Outro caminho',commanders:s.commanders,revealedZones:s.revealedZones,fallen:s.heroes.filter(h=>!h.hp).map(h=>h.id),campFood:s.campFood};log(s,reason);}
 function act(state,id,action,target){
  if(action==='interact'){
   const s=clone(state),h=s.heroes.find(h=>h.id===id),foes=h&&s.enemies.some(e=>e.zone===h.zone);if(s.result||!h||!h.hp||!h.ap)return {ok:false,state,error:'Escolha um herói de pé com uma ação.'};
   const token=s.explorations[h.zone];if(token&&!token.resolved){if(foes)return {ok:false,state,error:'Elimine os inimigos desta área antes de explorar.'};token.resolved=true;h.ap--;
    if(h.zone==='P3'){if(!s.revealedZones.includes('M3'))s.revealedZones.push('M3');log(s,H.find(d=>d.id===id).name+' explorou P3: posicionem imediatamente M3.');}
    else {for(const zone of ['B2','B3','B4'])if(!s.revealedZones.includes(zone))s.revealedZones.push(zone);const eligible=s.heroes.filter(a=>a.hp>0&&a.level<3).map(a=>a.id).sort(()=>Math.random()-.5);s.evolutionChoices=eligible.slice(0,2);log(s,H.find(d=>d.id===id).name+' alcançou a colina de C1. A boa vista revelou novos horizontes: posicionem B2, B3 e B4. Com o mapa completo, os heróis também descobriram uma nova evolução.');}
    return {ok:true,state:s};
   }
   if(h.zone!=='A1'||foes)return {ok:false,state,error:'Explore uma ficha livre de inimigos ou use o acampamento em A1.'};
   if(s.campDamage>0&&(h.food>0||s.campFood>0)){h.ap--;if(h.food>0)h.food--;else s.campFood--;s.foodSpent++;s.campDamage--;log(s,H.find(d=>d.id===id).name+' consumiu 1 alimento e reparou 1 dano ao acampamento.');return {ok:true,state:s};}
   if(h.food<FOOD_LIMIT&&s.campFood>0){const amount=Math.min(FOOD_LIMIT-h.food,s.campFood);h.ap--;h.food+=amount;s.campFood-=amount;log(s,H.find(d=>d.id===id).name+' repôs '+amount+' alimento(s) no acampamento.');return {ok:true,state:s};}
   return {ok:false,state,error:'Não há reparo ou reposição disponível em A1.'};
  }
  return W.act(state,id,action,target);
 }
 function retreatStep(e,s){return W.ZONES[e.zone].links.filter(z=>s.revealedZones.includes(z)).sort((a,b)=>W.distance(a,'M1',s)-W.distance(b,'M1',s))[0];}
 function plan(e,s){if(e.type==='heitor'&&e.retreating)return e.zone==='M1'?{type:'escape'}:{type:'retreat',zone:retreatStep(e,s)};if(e.stunned)return {type:'stun'};const metric=(a,b)=>W.distance(a,b,s),lure=H.taunt(s,e,metric,false),range=T.types[e.type]?.range||0,canAttack=!e.intimidated,targets=canAttack?s.heroes.filter(h=>h.hp>0&&metric(e.zone,h.zone)<=range).sort((a,b)=>metric(e.zone,a.zone)-metric(e.zone,b.zone)||b.hp-a.hp):[];if(lure&&canAttack&&metric(e.zone,lure.zone)<=range)return {type:'attack',target:lure.id};if(!lure&&targets.length)return {type:'attack',target:targets[0].id};if(!lure&&e.zone==='A1'&&canAttack)return {type:'camp'};const goal=lure?.zone||'A1',zone=W.ZONES[e.zone].links.filter(z=>s.revealedZones.includes(z)).sort((a,b)=>metric(a,goal)-metric(b,goal))[0];return zone?{type:'move',zone}:{type:'hold'};}
 function intent(e,s){const p=plan(e,s);return p.type==='escape'?'Entrar em Troia por M1':p.type==='retreat'?'Recuar para '+p.zone:p.type==='stun'?'Atordoado':e.intimidated?'Intimidado: não poderá atacar nesta resposta':p.type==='attack'?'Atacar '+H.find(h=>h.id===p.target).name:p.type==='camp'?'Causar 1 dano ao acampamento':p.type==='move'?'Avançar para '+p.zone:'Manter posição';}
 function beginRetreat(s,e){e.hp=1;if(e.type==='heitor'){if(e.zone==='M1'){s.enemies=s.enemies.filter(a=>a.id!==e.id);s.commanders.heitor='retreated';log(s,'Heitor atravessou M1 e ficou protegido pelas muralhas.');return;}if(!e.retreating)log(s,'Heitor foi gravemente ferido e começou a recuar, uma área por resposta, em direção a M1.');e.retreating=true;s.commanders.heitor='retreating';}else{s.commanders[e.type]='retreated';s.enemies=s.enemies.filter(a=>a.id!==e.id);log(s,T.label(e)+' recuou gravemente ferido.');}}
 function resolveRebound(s,e,h){if(!h.hp||(T.types[e.type]?.range||0)!==0||e.zone!==h.zone)return;const raw=Math.floor(H.stats(h).attack/2),amount=Math.max(0,raw-(h.id==='odisseu'?0:e.armor));e.hp-=amount;if(amount)log(s,H.find(d=>d.id===h.id).name+' respondeu ao ataque: '+amount+' de dano'+(h.id==='odisseu'?' ignorando Armadura':'')+'.');if(['heitor','paris'].includes(e.type)&&e.hp<=1){beginRetreat(s,e);return;}if(e.hp<=0){s.enemies=s.enemies.filter(a=>a.id!==e.id);if(['eneias','sarpedon'].includes(e.type))s.commanders[e.type]='dead';log(s,T.label(e)+' morreu em combate.');}}
 function trojanTurn(state){const s=clone(state);if(s.result)return s;log(s,'Troia responde na rodada '+s.round+'.');for(const e of [...s.enemies]){if(!s.enemies.some(a=>a.id===e.id))continue;const intimidated=!!e.intimidated,p=plan(e,s);e.intimidated=false;if(p.type==='escape'){s.enemies=s.enemies.filter(a=>a.id!==e.id);s.commanders.heitor='retreated';log(s,'Heitor atravessou M1 e ficou protegido pelas muralhas.');continue;}if(p.type==='retreat'){e.zone=p.zone;if(e.zone==='M1'){s.enemies=s.enemies.filter(a=>a.id!==e.id);s.commanders.heitor='retreated';log(s,'Heitor completou a retirada por M1 e não pode mais ser atacado.');}else log(s,'Heitor recuou para '+e.zone+', aproximando-se de M1.');continue;}if(p.type==='stun'){e.stunned=false;continue;}if(p.type==='attack'){const h=s.heroes.find(h=>h.id===p.target),damage=H.damage(s,h,e.attack,log);log(s,T.label(e)+' atacou '+H.find(d=>d.id===h.id).name+': '+damage+' de dano.');resolveRebound(s,e,h);}else if(p.type==='camp'){if(s.guards.A1>0)s.guards.A1--;else s.campDamage++;log(s,'Pressão no acampamento: '+s.campDamage+'/2 danos.');}else if(p.type==='move'){e.zone=p.zone;if(intimidated)log(s,T.label(e)+' avançou sem atacar, ainda abalado, para '+e.zone+'.');}if(s.campDamage>=2||s.heroes.every(h=>!h.hp)){finish(s,'defeat',s.campDamage>=2?'O acampamento foi rompido.':'Todos os heróis caíram.');return s;}}
  s.guards={};s.defended++;const explored=s.explorations.P3.resolved&&s.explorations.C1.resolved;if(s.defended>=8&&explored&&s.heroes.some(h=>h.zone==='A1'&&h.hp>0)&&!s.enemies.some(e=>e.zone==='A1')){finish(s,'victory','A linha resistiu por oito respostas e o território foi completamente revelado. Os sobreviventes preparam a próxima operação.');return s;}if(s.round>=MAX_ROUNDS){finish(s,'defeat',explored?'A ofensiva ocupou a base antes de consolidar a oitava defesa.':'O tempo acabou antes que P3 e C1 fossem exploradas.');return s;}s.round++;for(const [zone,type]of waveEntries(s,s.round))spawn(s,zone,type);s.heroes.forEach(h=>{h.ap=h.hp?H.stats(h).actions:0;h.bonusActions=0;h.tauntRound=0;});return s;
 }
 function chooseEvolution(state,id){return W.chooseEvolution(state,id);}
 function validSave(s){const int=(n,a,b)=>Number.isInteger(n)&&n>=a&&n<=b;if(!s||s.version!==VERSION||s.mission!=='defesa'||!int(s.players,1,5)||!int(s.round,1,MAX_ROUNDS)||!int(s.campDamage,0,2)||!int(s.defended,0,8)||!int(s.campFood,0,99)||!Array.isArray(s.heroes)||!int(s.heroes.length,1,5)||new Set(s.heroes.map(h=>h.id)).size!==s.heroes.length||!s.heroes.every(h=>int(h.owner,1,s.players)&&int(h.food,0,FOOD_LIMIT)&&H.valid(h,s.round)&&s.revealedZones.includes(h.zone)))return false;if(s.playerNames!==undefined&&(!Array.isArray(s.playerNames)||s.playerNames.length!==s.players||s.playerNames.some(n=>typeof n!=='string'||!n.trim()||n.length>30)))return false;if(!s.explorations||Object.keys(s.explorations).sort().join(',')!=='C1,P3'||!Object.values(s.explorations).every(x=>typeof x.resolved==='boolean'))return false;const expected=[...MISSION_TWO_ZONES];if(s.explorations.P3.resolved)expected.push('M3');if(s.explorations.C1.resolved)expected.push('B2','B3','B4');if(!Array.isArray(s.revealedZones)||new Set(s.revealedZones).size!==s.revealedZones.length||expected.sort().join(',')!==s.revealedZones.slice().sort().join(','))return false;if(!s.commanders||!['heitor','paris','eneias','sarpedon'].every(id=>['unseen','active','retreating','retreated','dead'].includes(s.commanders[id])))return false;if(!Array.isArray(s.enemies)||!s.enemies.every(e=>T.types[e.type]&&s.revealedZones.includes(e.zone)&&int(e.hp,1,T.types[e.type].hp)&&(e.retreating===undefined||typeof e.retreating==='boolean')&&(e.intimidated===undefined||typeof e.intimidated==='boolean')&&(!e.retreating||e.type==='heitor'&&e.hp===1)))return false;return ['heroes','end'].includes(s.phase)&&[null,'victory','defeat'].includes(s.result)&&(s.phase==='end')===!!s.result&&Array.isArray(s.log);}
 return {...W,VERSION,MAX_ROUNDS,newGame,act,interaction,trojanTurn,validSave,intent,chooseEvolution,waves:(s,r)=>waveEntries(s,r).map(([z,t])=>T.types[t].name+' em '+z)};
});
