(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./muralhas.js'));else root.TroyDefense=factory(root.TroyWalls);})(typeof globalThis!=='undefined'?globalThis:this,function(W){
 const MAX_ROUNDS=8,H=W.HEROES,T=W.TROOPS,clone=s=>JSON.parse(JSON.stringify(s));
 function log(s,msg){s.log.unshift(msg);s.log=s.log.slice(0,80);}
 function spawn(s,zone,type){s.enemies.push(T.create('e'+s.nextEnemy++,zone,type));}
 function newGame(options={}){const s=W.newGame(options);s.version=1;s.mission='defesa';s.campDamage=0;s.defended=0;s.enemies=[];s.nextEnemy=1;s.log=[];s.heroes.forEach(h=>h.weapon=true);s.weaponStock=0;spawn(s,'P3','lanceiro');if(s.heroes.length>=4)spawn(s,'P7','lanceiro');log(s,'Segurem a linha: resistam a seis respostas de Troia e terminem com A1 livre e um defensor de pé.');return s;}
 function waves(s,round){return ({2:[['P3','explorador']],3:[['P7','heitor']],4:[['M4','paris']],5:[['P4','lanceiro']],6:[['P3','guarda']]})[round]||[];}
 function interaction(s,h){return {label:'Reparar acampamento',detail:'1 ação + 1 comida · remove 1 dano',available:h.zone==='A1'&&s.campDamage>0&&h.food>0};}
 function finish(s,result,reason){s.result=result;s.phase='end';s.reason=reason;if(result==='victory')s.outcome={completed:'defesa',next:'Outro caminho'};log(s,reason);}
 function act(state,id,action,target){if(action==='interact'){const s=clone(state),h=s.heroes.find(h=>h.id===id);if(s.result||!h||!h.hp||!h.ap||!interaction(s,h).available||s.enemies.some(e=>e.zone==='A1'))return {ok:false,state,error:'Repare em A1 livre de inimigos, com uma ação e uma comida.'};h.ap--;h.food--;s.foodSpent++;s.campDamage--;log(s,H.find(d=>d.id===id).name+' reparou 1 dano ao acampamento.');return {ok:true,state:s};}return W.act(state,id,action,target);}
 function plan(e,s){if(e.stunned)return {type:'stun'};const lure=H.taunt(s,e,W.distance,false),range=T.types[e.type]?.range||0;
 const targets=s.heroes.filter(h=>h.hp>0&&W.distance(e.zone,h.zone)<=range).sort((a,b)=>W.distance(e.zone,a.zone)-W.distance(e.zone,b.zone)||b.hp-a.hp);
 if(lure&&W.distance(e.zone,lure.zone)<=range)return {type:'attack',target:lure.id};if(!lure&&targets.length)return {type:'attack',target:targets[0].id};if(!lure&&e.zone==='A1')return {type:'camp'};const goal=lure?.zone||'A1';return {type:'move',zone:W.ZONES[e.zone].links.slice().sort((a,b)=>W.distance(a,goal)-W.distance(b,goal))[0]};}
 function intent(e,s){const p=plan(e,s);return p.type==='stun'?'Atordoado':p.type==='attack'?'Atacar '+H.find(h=>h.id===p.target).name:p.type==='camp'?'Causar 1 dano ao acampamento':'Avançar para '+p.zone;}
 function trojanTurn(state){const s=clone(state);if(s.result)return s;log(s,'Troia responde na rodada '+s.round+'.');for(const e of [...s.enemies]){const p=plan(e,s);if(p.type==='stun'){e.stunned=false;continue;}if(p.type==='attack'){const h=s.heroes.find(h=>h.id===p.target);const damage=H.damage(s,h,e.attack,log);log(s,T.label(e)+' atacou '+h.id+': '+damage+' de dano.');if(h.hp>0){e.hp-=Math.max(0,Math.ceil(H.stats(h).attack/2)-e.armor);if(e.hp<=0)s.enemies=s.enemies.filter(a=>a.id!==e.id);}}else if(p.type==='camp'){if(s.guards.A1>0)s.guards.A1--;else s.campDamage++;log(s,'Pressão no acampamento: '+s.campDamage+'/5 danos.');}else e.zone=p.zone;if(s.campDamage>=5||s.heroes.every(h=>!h.hp)){finish(s,'defeat',s.campDamage>=5?'O acampamento foi rompido.':'Todos os heróis caíram.');return s;}}
 s.guards={};s.defended++;if(s.defended>=6&&s.heroes.some(h=>h.zone==='A1'&&h.hp>0)&&!s.enemies.some(e=>e.zone==='A1')){finish(s,'victory','A linha resistiu. Heitor e Páris recuam com o restante da ofensiva; os aqueus precisam buscar outro caminho para Troia.');return s;}if(s.round>=MAX_ROUNDS){finish(s,'defeat','A ofensiva ocupou a base antes de consolidar a defesa.');return s;}s.round++;for(const [zone,type]of waves(s,s.round))spawn(s,zone,type);s.heroes.forEach(h=>{h.ap=h.hp?H.stats(h).actions:0;h.bonusActions=0;h.tauntRound=0;});return s;}
 function validSave(s){if(!s||s.mission!=='defesa'||s.version!==1||!Number.isInteger(s.campDamage)||s.campDamage<0||s.campDamage>5||!Number.isInteger(s.defended)||s.defended<0||s.defended>8||s.round>8)return false;const copy=clone(s);copy.version=W.VERSION;copy.mission='muralhas';copy.result=null;copy.phase='heroes';// Defense permits enemy occupation of A1; validate their remaining fields through the shared schema.
 copy.enemies.forEach(e=>{if(e.zone==='A1')e.zone='A2';});if(!W.validSave(copy))return false;return ['heroes','end'].includes(s.phase)&&[null,'victory','defeat'].includes(s.result)&&(s.phase==='end')===!!s.result&&(s.result!=='victory'||s.defended>=6&&s.campDamage<5&&s.heroes.some(h=>h.zone==='A1'&&h.hp>0)&&!s.enemies.some(e=>e.zone==='A1'));}
 return {...W,VERSION:1,MAX_ROUNDS,newGame,act,interaction,trojanTurn,validSave,intent,waves:(s,r)=>waves(s,r).map(([z,t])=>T.types[t].name+' em '+z)};
});
