'use strict';
function puzzleMap(s,selected){
 const regions={};
 const project=(x,y)=>[x,(55+y*2/3)/1.02];
 for(const [id,r] of Object.entries(window.TroyTerritory))if(G.ZONES[id]){const [x,y]=project(r.x,r.y);regions[id]={x,y,shared:true,polygon:r.polygon.split(' ').map(p=>project(...p.split(',').map(Number)).join(',')).join(' ')};}
 regions.P4={x:27,y:43,polygon:'9,64.705882 23,64.705882 32,71.24183 43,49 47,30 30,25 13,36'};
 regions.P5={x:76,y:43,polygon:'60,65.03268 79,63.071895 91,68.300654 94,40 88,27 65,28 54,43'};
 regions.M1={x:51,y:18,polygon:'40,9 59,9 63,20 55,29 47,30 38,23'};
 regions.M2={x:82,y:20,polygon:'75,10 89,11 96,20 88,27 76,29 70,22'};
 const art=Object.entries(regions).map(([id,r])=>'<clipPath id="piece-'+id+'"><polygon points="'+r.polygon+'"/></clipPath>').join('');
 const pieces=Object.entries(regions).map(([id,r])=>'<image href="assets/'+(r.shared?'territorio-troia.png':'aproximacao-troia.png')+'" x="0" y="'+(r.shared?55/1.02:0)+'" width="100" height="'+(100*2/3/1.02)+'" preserveAspectRatio="none" clip-path="url(#piece-'+id+')"/>').join('');
 const hero=s.heroes.find(h=>h.id===selected),edges=[];
 for(const [id,z] of Object.entries(G.ZONES))for(const n of z.links)if(id<n){const a=regions[id],b=regions[n];edges.push(`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/>`);}
 return `<section class="map-panel natural-panel" aria-label="Reconhecimento das muralhas"><div class="section-label"><span>BASE → ACESSOS DE TROIA</span><span>MISSÃO 02</span></div><p class="map-key"><span>━━ Fronteira</span><span>┄┄ Acesso permitido</span><span>⚑ A1 segura</span></p><div class="puzzle-scroll" tabindex="0" aria-label="Mapa panorâmico: deslize para os lados"><div class="natural-map muralhas-map"><svg class="territory-overlay modular-art" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Peças originais reutilizadas e extensão da planície até Troia"><defs>${art}</defs>${pieces}</svg><svg class="territory-overlay" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><g class="region-boundaries">${Object.entries(regions).map(([id,r])=>`<polygon points="${r.polygon}" class="${id===hero.zone?'active-region':''}"/>`).join('')}</g><g class="territory-routes">${edges.join('')}</g></svg>${Object.entries(regions).map(([id,r])=>{
 const status=id==='A1'?'⚑ Base segura':id==='B1'?(s.ambush?'Emboscada revelada':'⚠ Sinais de patrulha'):id.startsWith('M')?(s.scouted.includes(id)?'✓ Reconhecido':'⌕ Reconhecer'):'';
 return `<div class="territory-marker ${hero.zone===id?'selected':''}" style="left:${r.x}%;top:${r.y}%" aria-label="${G.ZONES[id].name}: ${status}"><div class="territory-title"><b>${id}</b> ${G.TERRAINS[id[0]].name}</div>${status?`<small>${status}</small>`:''}<div class="territory-tokens">${s.heroes.filter(h=>h.zone===id).map(h=>`<span class="token ${h.hp===0?'down':''}" title="${G.HEROES.find(d=>d.id===h.id).name}">${G.HEROES.find(d=>d.id===h.id).initial} ${h.hp}♥</span>`).join('')}${s.enemies.filter(e=>e.zone===id).map(e=>`<span class="token enemy">Tr${e.id.slice(1)} ${e.hp}♥</span>`).join('')}</div>${s.guards[id]?`<small>🛡 ${s.guards[id]}</small>`:''}</div>`;
 }).join('')}<div class="camp-miniatures walls-camp" role="img" aria-label="Base aqueia estabelecida"><span></span><span></span><span></span></div><span class="geography-label sea-label">PEÇAS DA PRAIA RETIRADAS</span></div></div><div class="map-note"><b>Contornos claros: limites. Dourado tracejado: acessos.</b> Reconheçam M1/M2 e voltem a A1. B1 tem um ponto de risco anunciado. A1, A2, P1–P3 e B1–B2 preservam a arte e o recorte da missão 1. P4/P5 e M1/M2 ampliam a montagem. As junções da arte ainda serão ajustadas para impressão. Deslize o mapa para os lados em telas pequenas.</div></section>`;
}
