'use strict';
const G = window.TroyWalls;
const SAVE_KEY = 'ilia-muralhas-v2';
let state = null, selected = 'aquiles', pending = null, confirmation = null, saved = null, storageOK = true;
let setup={players:1,heroes:['aquiles','ajax','odisseu'],owners:[1,1,1]};
let completed=false;try{completed=localStorage.getItem('ilia-campanha-desembarque')==='complete';}catch(e){}
const app = document.getElementById('app');
const esc = value => String(value).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
try { const raw = localStorage.getItem(SAVE_KEY); if(raw){const parsed=JSON.parse(raw);if(G.validSave(parsed))saved=parsed;} } catch(e){storageOK=false;}
function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));saved=state;if(state.result==='victory'){let prior=null;try{prior=JSON.parse(localStorage.getItem('ilia-campanha-v1'));}catch(e){}localStorage.setItem('ilia-campanha-v1',JSON.stringify(window.TroyCampaign.record(prior,state.outcome,state.heroes,state.players)));}}catch(e){storageOK=false;}}
let noticeTimer;
function notice(text){document.getElementById('notice').textContent=text;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>document.getElementById('notice').textContent='',6000);}
function button(label,command,extra='',disabled=false,cls='action'){return `<button class="${cls}" data-command="${command}" ${extra} ${disabled?'disabled':''}>${label}</button>`;}
function briefing(){
 const count=Math.max(3,setup.players),valid=setup.heroes.length===count&&new Set(setup.owners).size===setup.players;
 app.innerHTML=`<section class="briefing"><p class="eyebrow">CAMPANHA / CAPÍTULO 02 DE 06</p><h1>Diante das muralhas</h1><p class="lead">A base está estabelecida. Avancem até os dois acessos de Troia, descubram suas defesas e voltem com a informação. Derrubar a muralha não é o objetivo.</p><p><a href="./">← Desembarque</a> · <a href="campanha.html">Plano da campanha</a></p>
 ${saved&&!saved.result?`<div class="resume-box"><p>Reconhecimento salvo: rodada ${saved.round}, ${saved.scouted.length}/2 acessos observados.</p>${button('Continuar missão','continue','',false,'button')}</div>`:''}
 <div class="brief-grid"><div class="box"><h3>Reconhecer M1 e M2</h3><p>Todos partem de A1. Cheguem a cada acesso e usem <b>Reconhecer acesso</b>: 1 ação, sem inimigos na região. Vocês têm até 14 rodadas.</p><p>A1 é uma base segura: inimigos não entram e ela não ataca por vocês.</p></div><div class="box"><h3>Preparar a retirada</h3><p>O segundo reconhecimento chama ${Math.ceil(count/2)} grupos nos acessos e inicia a retirada. Há a rodada atual e mais seis, sem ultrapassar a rodada 14.</p><p>Reúnam <b>todos de pé em A1</b> e gastem 1 ação para concluir. Não é necessário eliminar todos os inimigos.</p></div></div>
 <div class="box"><h3>Indícios no bosque</h3><p>Há pegadas e sinais de patrulha em B1. A primeira chegada de um herói a B1 revela ${count===5?'dois grupos':'um grupo'} em B2, apenas uma vez. Eles agem na próxima resposta de Troia. A rota A1 → A2 → P1 → P4 → M1 evita esse ponto de risco.</p><p>As tropas guardam os acessos até alguém se aproximar a duas regiões. Após o primeiro reconhecimento, perseguem heróis fora da base. Um reforço chega a M1 na rodada 5, se a retirada ainda não começou.</p></div>
 <section class="team-setup box" aria-label="Preparar equipe"><h2>Sua expedição</h2><label for="player-count">Quantas pessoas vão jogar?</label><select id="player-count">${[1,2,3,4,5].map(n=>`<option value="${n}" ${n===setup.players?'selected':''}>${n} ${n===1?'jogador':'jogadores'}</option>`).join('')}</select><p>Escolha ${count} heróis (${setup.heroes.length}/${count}). ${setup.players===1?'No solo, você controla os três escolhidos.':setup.players===2?'Distribuam os três heróis entre os dois jogadores.':'Cada pessoa controla um herói.'} Partida local no mesmo aparelho.</p>
  <div class="hero-picker">${G.HEROES.map(h=>`<button class="hero-choice ${setup.heroes.includes(h.id)?'chosen':''}" data-command="toggle-hero" data-id="${h.id}" aria-pressed="${setup.heroes.includes(h.id)}"><b>${h.name}</b><small>${h.role}</small><span>${setup.heroes.includes(h.id)?'✓ Selecionado':'Selecionar'}</span></button>`).join('')}</div>
  <div class="ownership">${setup.heroes.map((id,i)=>{const h=G.HEROES.find(h=>h.id===id);return `<div><label for="owner-${id}">${h.name}</label><select id="owner-${id}" data-owner="${i}" ${setup.players===1?'disabled':''}>${Array.from({length:setup.players},(_,n)=>`<option value="${n+1}" ${setup.owners[i]===n+1?'selected':''}>Jogador ${n+1}</option>`).join('')}</select></div>`;}).join('')}</div>
  <details><summary>Conhecer as habilidades dos cinco heróis</summary>${G.HEROES.map(h=>`<h3>${h.name}</h3><ul>${h.cards.map(c=>`<li><b>${c.name}:</b> ${c.text}</li>`).join('')}</ul>`).join('')}</details>
  <p class="saved-note">${count} heróis: ${count>=4?'duas guardas iniciais':'uma guarda inicial'}; ${Math.ceil(count/2)} grupos no contra-ataque; ${count===5?2:1} na emboscada.</p>
  ${!valid?'<p class="setup-error">Escolha a quantidade indicada e atribua ao menos um herói a cada jogador.</p>':''}
  <div class="actions-row">${button(saved&&!saved.result?'Começar nova missão':'Iniciar reconhecimento →','start','',!valid,'button')}</div>${confirmation==='new'?newConfirm():''}</section>
 <details class="log"><summary>Território, vitória e derrota</summary><p>M1 liga-se a P1 e M2. M2 liga-se a M1 e B1. As demais conexões douradas seguem a planície e o bosque até A1. O mar, as praias e a colina não são casas deste capítulo.</p><p>Derrota: todos caídos ou término do prazo sem reconhecer os dois acessos e concluir a retirada. Socorram aliados caídos antes de voltar.</p><p>A faixa de muralhas é uma extensão modular para testar o cenário. A arte final será feita depois da validação.</p></details><p class="saved-note">Missão disponível para teste independente. Não consome recursos da campanha. Equipe e progresso têm salvamento próprio; vencer registra as informações dos dois acessos para o futuro capítulo 3.</p></section>`;
}

function newConfirm(){return `<div class="confirm-row"><p>Começar outra missão substitui o progresso salvo neste navegador.</p><div class="actions-row">${button('Começar do início','new-confirm','',false,'quiet')}${button('Cancelar','cancel','',false,'quiet')}</div></div>`;}
function mapHTML(){return puzzleMap(state,selected);}
function targets(action,h){
  if(action==='move')return G.ZONES[h.zone].links.map(z=>[z,G.ZONES[z].name]);
  if(action==='attack')return state.enemies.filter(e=>e.zone===h.zone).map(e=>[e.id,`Grupo ${e.id.slice(1)} · ${e.hp}♥`]);
  if(action==='rescue')return state.heroes.filter(a=>a.hp===0&&a.zone===h.zone).map(a=>[a.id,G.HEROES.find(d=>d.id===a.id).name]);
  if(action.startsWith('card:')){
    const c=G.HEROES.find(d=>d.id===h.id).cards[Number(action.slice(5))];
    if(['attack','ranged','charge'].includes(c.type))return state.enemies.filter(e=>c.type==='charge'?G.distance(h.zone,e.zone)===1:G.distance(h.zone,e.zone)<=(c.type==='ranged'?1:0)).map(e=>[e.id,`Grupo ${e.id.slice(1)} · ${G.ZONES[e.zone].name} · ${e.hp}♥`]);
    if(c.type==='refresh')return state.heroes.filter(a=>a.id!==h.id&&a.zone===h.zone&&a.hp>0&&a.used.length).map(a=>[a.id,G.HEROES.find(d=>d.id===a.id).name]);
    if(c.type==='healAlly')return state.heroes.filter(a=>a.id!==h.id&&a.zone===h.zone&&a.hp<6).map(a=>[a.id,G.HEROES.find(d=>d.id===a.id).name]);
    if(c.type==='guide')return state.heroes.filter(a=>a.id!==h.id&&a.hp>0&&a.zone===h.zone).flatMap(a=>G.ZONES[h.zone].links.map(z=>[a.id+':'+z,G.HEROES.find(d=>d.id===a.id).name+' → '+G.ZONES[z].name]));
    if(c.type==='sprint')return Object.keys(G.ZONES).filter(z=>z!==h.zone&&G.distance(h.zone,z)<=2).map(z=>[z,G.ZONES[z].name]);
  }return null;
}
function commandHTML(){
  const h=state.heroes.find(x=>x.id===selected),d=G.HEROES.find(x=>x.id===selected),disabled=!!state.result||h.hp===0||h.ap===0,foes=state.enemies.some(e=>e.zone===h.zone);
  const interaction=G.interaction(state,h),hasInteraction=interaction.available;
  return `<aside class="command"><div class="hero-tabs" aria-label="Escolher herói">${state.heroes.map(a=>button(`${G.HEROES.find(d=>d.id===a.id).name}<small>J${a.owner} · ${a.hp===0?'Caído':a.ap+'/2 ações · '+a.hp+'♥'}</small>`,'hero',`data-id="${a.id}" aria-pressed="${a.id===selected}"`,false,'hero-tab '+(a.id===selected?'active':''))).join('')}</div><div class="box"><div class="hero-heading"><h2>${d.name}</h2><span>${h.hp}/6 ♥</span></div><p class="context">${d.role} · Jogador ${h.owner} · ${G.ZONES[h.zone].name}${h.cargo?' · ▣ Carregando uma caixa':''} · <b>${h.ap} ação(ões)</b>${h.hp===0?' · Precisa ser socorrido':''}</p><div class="action-grid">${button('Mover<small>1 área conectada</small>','action','data-action="move"',disabled)}${button('Atacar<small>2 de dano nesta área</small>','action','data-action="attack"',disabled||!foes)}${button(`${interaction.label}<small>${interaction.detail}</small>`,'action','data-action="interact"',disabled||foes||!hasInteraction)}${button('Recuperar<small>Habilidades + 1 de vida</small>','action','data-action="rest"',disabled||foes||(!h.used.length&&h.hp===6))}${state.heroes.some(a=>a.hp===0&&a.zone===h.zone)?button('Socorrer<small>Levante um aliado com 2 de vida</small>','action','data-action="rescue"',disabled):''}</div>${pending?`<div class="target-box"><p>Escolha o alvo ou destino. Custo: 1 ação.</p><div class="target-options">${(targets(pending,h)||[]).map(([id,label])=>button(esc(label),'target',`data-target="${esc(id)}"`,false,'')).join('')}${button('Cancelar','cancel','',false,'quiet')}</div></div>`:''}<p class="ability-title">HABILIDADES · CADA USO CUSTA 1 AÇÃO</p>${d.cards.map((c,i)=>{const t=targets('card:'+i,h);const unavailable=(t&&t.length===0)||(c.type==='heal'&&h.hp===6);return button(`<strong>${c.name}${h.used.includes(i)?' · esgotada':''}</strong><small>${c.text}</small>`,'action',`data-action="card:${i}"`,disabled||h.used.includes(i)||unavailable,'card '+(pending==='card:'+i?'selected':''));}).join('')}<p class="saved-note">Recuperar deixa as três habilidades prontas novamente.</p></div>${!state.result?button('Encerrar rodada → Troia responde','end','',false,'button turn-end'):''}${confirmation==='end'?`<div class="confirm-row"><p>Ainda há ${state.heroes.reduce((n,a)=>n+(a.hp>0?a.ap:0),0)} ações disponíveis. Encerrar descarta essas ações.</p><div class="actions-row">${button('Encerrar mesmo assim','end-confirm','',false,'quiet')}${button('Continuar jogando','cancel','',false,'quiet')}</div></div>`:''}<p class="saved-note">${storageOK?'Partida salva neste navegador.':'Não foi possível salvar. Mantenha esta página aberta.'}</p></aside>`;
}
function render(){
 if(!state){briefing();return;}const pan=document.querySelector('.puzzle-scroll')?.scrollLeft||0;
 app.innerHTML=`<div class="mission-header"><div><p class="eyebrow">MISSÃO 02 / EM EQUIPE</p><h1>Diante das muralhas</h1><p>${state.scouted.length===2?'Retirada! Voltem todos de pé a A1 e usem Concluir retirada.':'Reconheçam M1 e M2. Os acessos precisam estar livres de inimigos.'}</p></div><div class="metrics"><div class="metric">RODADA<strong>${state.round}/${G.MAX_ROUNDS}</strong></div><div class="metric">ACESSOS<strong>${state.scouted.length}/2</strong></div><div class="metric">PRAZO<strong>${state.retreatDeadline?'Rodada '+state.retreatDeadline:'Rodada 14'}</strong></div></div></div>
 ${state.result?`<section class="result ${state.result}"><h2>${state.result==='victory'?'Informações a salvo.':'O reconhecimento foi interrompido.'}</h2><p>${esc(state.reason)}</p>${state.result==='victory'?'<p>Informações de M1 e M2 registradas. Próximo capítulo: <b>Segurar a linha</b>, ainda em desenvolvimento.</p>':''}<div class="actions-row">${button('Jogar novamente','new-confirm','',false,'button')}<a class="button secondary" href="./">Voltar ao Desembarque</a></div></section>`:''}
 <ol class="mission-steps"><li class="${state.scouted.includes('M1')?'done':''}">1 · Reconhecer M1</li><li class="${state.scouted.includes('M2')?'done':''}">2 · Reconhecer M2</li><li class="${state.result==='victory'?'done':''}">3 · Retornar a A1</li></ol><div class="game-layout"><div>${puzzleMap(state,selected)}<section class="box threats"><h3>Próxima resposta de Troia</h3>${state.result?'<p>Missão encerrada.</p>':state.enemies.map(e=>`<div class="threat-row"><b>Grupo ${e.id.slice(1)} · ${e.zone}</b><span>${G.intent(e,state)}</span></div>`).join('')||'<p>Nenhum grupo em campo.</p>'}<p class="reinforcements">${state.result?'':G.waves(state,state.round+1).length?'Próxima rodada: reforço em M1.':'Sem reforço programado na próxima rodada.'}</p></section><details class="log"><summary>Gatilhos e avisos</summary><p>B1: ${state.ambush?'emboscada já revelada; não se repete.':'primeira chegada revela uma patrulha em B2, que age na próxima resposta.'}</p><p>Reconhecer o segundo acesso chama ${Math.ceil(state.heroes.length/2)} grupos em M1/M2 e inicia o prazo de retirada. A1 é segura.</p></details><details class="log"><summary>Registro · ${state.log.length} acontecimentos</summary><ol>${state.log.map(msg=>`<li>${esc(msg)}</li>`).join('')}</ol></details></div>${commandHTML()}</div><footer><a href="./">← Desembarque</a> · <a href="campanha.html">Campanha</a> · ${button('Preparar outra equipe','setup','',false,'quiet')}</footer>${confirmation==='new'?newConfirm():''}`;
 document.querySelector('.puzzle-scroll').scrollLeft=pan;
}

function perform(action,target){const result=G.act(state,selected,action,target);if(!result.ok){notice(result.error);return;}state=result.state;pending=null;confirmation=null;persist();render();if(action==='interact')notice(state.log[0]);if(state.result){notice(state.reason);window.scrollTo({top:0,behavior:'smooth'});}}
function endRound(){state=G.trojanTurn(state);pending=null;confirmation=null;persist();render();notice(state.result?state.reason:'Troia respondeu. Rodada '+state.round+' iniciada.');if(state.result)window.scrollTo({top:0,behavior:'smooth'});}
app.addEventListener('click',event=>{
  const b=event.target.closest('button[data-command]');if(!b||b.disabled)return;
  const c=b.dataset.command;
  if(['start','new-confirm'].includes(c)){try{G.newGame(setup);}catch(e){notice(e.message);return;}}
  if(c==='start'){if((state&&!state.result)||(saved&&!saved.result)){confirmation='new';render();}else{state=G.newGame(setup);selected=state.heroes[0].id;persist();render();window.scrollTo(0,0);}}
  else if(c==='new-confirm'){state=G.newGame(setup);selected=state.heroes[0].id;pending=null;confirmation=null;persist();render();window.scrollTo(0,0);}
  else if(c==='continue'){state=JSON.parse(JSON.stringify(saved));selected=state.heroes[0].id;setup={players:state.players,heroes:state.heroes.map(h=>h.id),owners:state.heroes.map(h=>h.owner)};render();}
  else if(c==='setup'){state=null;pending=null;confirmation=null;briefing();}
  else if(c==='toggle-hero'){const id=b.dataset.id,i=setup.heroes.indexOf(id);if(i>=0)setup.heroes.splice(i,1);else if(setup.heroes.length<Math.max(3,setup.players))setup.heroes.push(id);else{notice('Desmarque um herói antes de escolher outro.');return;}setup.owners=setup.heroes.map((_,i)=>i%setup.players+1);briefing();}
  else if(c==='hero'){selected=b.dataset.id;pending=null;confirmation=null;render();}
  else if(c==='cancel'){pending=null;confirmation=null;render();}
  else if(c==='action'){const a=b.dataset.action,h=state.heroes.find(x=>x.id===selected),t=targets(a,h);confirmation=null;if(t){if(!t.length){notice('Não há um alvo válido para esta ação.');return;}pending=a;render();}else perform(a);}
  else if(c==='target'){if(pending)perform(pending,b.dataset.target);}
  else if(c==='end'){if(state.heroes.some(h=>h.hp>0&&h.ap>0)){confirmation='end';pending=null;render();}else endRound();}
  else if(c==='end-confirm')endRound();
});
app.addEventListener('change',event=>{if(event.target.id==='player-count'){setup.players=Number(event.target.value);const count=Math.max(3,setup.players);for(const h of G.HEROES)if(setup.heroes.length<count&&!setup.heroes.includes(h.id))setup.heroes.push(h.id);setup.heroes=setup.heroes.slice(0,count);setup.owners=setup.heroes.map((_,i)=>i%setup.players+1);briefing();}else if(event.target.dataset.owner!==undefined){setup.owners[Number(event.target.dataset.owner)]=Number(event.target.value);briefing();}});
const rules=document.getElementById('rules');document.getElementById('rules-button').addEventListener('click',()=>rules.showModal());document.getElementById('close-rules').addEventListener('click',()=>rules.close());rules.addEventListener('click',e=>{if(e.target===rules){const r=rules.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)rules.close();}});
try{const previous=JSON.parse(localStorage.getItem('ilia-campanha-v1'));const old=JSON.parse(localStorage.getItem('ilia-desembarque-v2'));const team=previous?.team||(old&&{players:old.players,heroes:old.heroes.map(h=>h.id),owners:old.heroes.map(h=>h.owner)});if(team){G.newGame(team);setup=team;}}catch(e){}
render();
