'use strict';
// Só as peças desta missão: o arquivo de território tem as peças de todas as missões.
function missionRegions(){return Object.fromEntries(Object.entries(window.TroyTerritory).filter(([id])=>G.ZONES[id]));}
function puzzleMap(s,selected){
  const regions=missionRegions(),hero=s.heroes.find(h=>h.id===selected),edges=[];
  for(const [id,z] of Object.entries(G.ZONES))for(const next of z.links)if(id<next){const a=regions[id],b=regions[next];edges.push(`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/>`);}
  return `<section class="map-panel natural-panel" aria-label="Território do Desembarque"><div class="section-label"><span>COSTA DA TRÓADE</span><span>10 PEÇAS · MISSÃO 1</span></div><label class="route-switch"><input type="checkbox" id="show-routes"> Mostrar acessos permitidos</label><details class="map-controls"><summary>Como ler este território</summary><p>Somente as peças desta missão estão expostas. As linhas douradas mostram as conexões permitidas: 1 movimento por região. Água, rochedos e espaços sem contorno não são casas. C2 faz parte desta missão.</p></details><div class="puzzle-scroll" tabindex="0" aria-label="Mapa panorâmico; deslize para explorar"><div class="natural-map" style="aspect-ratio:3/2;min-width:820px;overflow:hidden;margin-top:-13%"><svg class="landscape" viewBox="0 0 1536 1024" preserveAspectRatio="none" role="img" aria-label="Recorte da missão 1 do tabuleiro principal final"><image href="assets/setup/stage-5.png?v=3" width="1536" height="1024" preserveAspectRatio="none"/></svg><svg class="territory-overlay route-overlay" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><g class="territory-routes">${edges.join('')}</g></svg>${Object.entries(regions).map(([id,r])=>{
    const allies=s.heroes.filter(h=>h.zone===id),enemies=s.enemies.filter(e=>e.zone===id);
    const status=id==='A1'?(s.built?'Acampamento instalado':'Clareira · construir'):(s.supplies[id]||0)?'▣':'';
    return `<div class="board-counters ${id===hero.zone?'selected':''}" style="left:${r.x}%;top:${r.y}%" aria-label="${G.ZONES[id].name}">${id!=='A1'&&s.supplies[id]>0?'<span class="exploration-token" role="img" aria-label="Ficha de exploração">⌕</span>':status?`<small>${status}</small>`:''}<div class="territory-tokens">${allies.map(h=>`<span class="unit-token greek-unit ${h.hp===0?'down':''}" title="${G.HEROES.find(d=>d.id===h.id).name} · ${h.hp} de vida"><span aria-hidden="true">♙</span><b>${h.hp}</b></span>`).join('')}${enemies.map(e=>`<span class="unit-token ${G.TROOPS.types[e.type]?.hero?'trojan-hero-unit':'trojan-unit'} troop-${e.type}" title="${G.TROOPS.label(e)} · ${e.hp} de vida"><span aria-hidden="true">${G.TROOPS.types[e.type]?.hero?'♛':'♟'}</span><b>${e.hp}</b></span>`).join('')}</div>${s.guards[id]?`<small>🛡 ${s.guards[id]}</small>`:''}</div>`;
  }).join('')}${s.built?'<div class="camp-miniatures" style="left:9%;top:62%" role="img" aria-label="Três tendas construídas, representadas por marcadores removíveis"><span>⛺</span><span>⛺</span><span>⛺</span></div>':''}</div></div><div class="map-note"><b>N1–N4: use a faixa de areia; a água é intransitável.</b> As linhas douradas correspondem às opções de Mover. A arte já contém tendas; o marcador de instalação indica quando a base está pronta.</div></section>`;
}
