'use strict';
function puzzleMap(s,selected){
  const regions=window.TroyTerritory,hero=s.heroes.find(h=>h.id===selected),edges=[];
  for(const [id,z] of Object.entries(G.ZONES))for(const next of z.links)if(id<next){const a=regions[id],b=regions[next];edges.push(`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/>`);}
  return `<section class="map-panel natural-panel" aria-label="Território do Desembarque"><div class="section-label"><span>COSTA DA TRÓADE</span><span>9 REGIÕES EM TERRA</span></div><p class="map-key"><span>━━ Fronteira</span><span>┄┄ Acesso permitido</span></p><details class="map-controls"><summary>Como ler este território</summary><p>Os contornos indicam regiões de ação, ainda não cortes de impressão. As linhas douradas mostram as conexões permitidas: 1 movimento por região. Água, rochedos e espaços sem contorno não são casas. A colina está reservada para outro capítulo.</p></details><div class="puzzle-scroll" tabindex="0" aria-label="Mapa panorâmico; deslize para explorar"><div class="natural-map"><img class="landscape" src="assets/territorio-troia.png" alt="Costa com praia seca, clareira de acampamento à esquerda, planície central, bosque à direita e colina ao norte" width="1536" height="1024"><svg class="territory-overlay" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><g class="region-boundaries">${Object.entries(regions).map(([id,r])=>`<polygon class="${id===hero.zone?'active-region':''}" points="${r.polygon}"/>`).join('')}</g><g class="territory-routes">${edges.join('')}</g></svg><span class="geography-label hill-label">COLINA · OUTRA MISSÃO</span><span class="geography-label sea-label">MAR EGEU · INTRANSITÁVEL</span>${Object.entries(regions).map(([id,r])=>{
    const allies=s.heroes.filter(h=>h.zone===id),enemies=s.enemies.filter(e=>e.zone===id);
    const status=id==='A1'?(s.built?'Acampamento instalado':'Clareira · construir'):(s.supplies[id]||0)?'▣ '+s.supplies[id]+' caixa(s)':'';
    return `<div class="territory-marker ${id===hero.zone?'selected':''}" style="left:${r.x}%;top:${r.y}%" aria-label="${G.ZONES[id].name}"><div class="territory-title"><b>${id}</b> ${G.TERRAINS[id[0]].name}</div>${status?`<small>${status}</small>`:''}<div class="territory-tokens">${allies.map(h=>`<span class="token ${h.hp===0?'down':''}" title="${G.HEROES.find(d=>d.id===h.id).name}">${G.HEROES.find(d=>d.id===h.id).initial} ${h.hp}♥${h.cargo?' ▣':''}</span>`).join('')}${enemies.map(e=>`<span class="token enemy">Tr${e.id.slice(1)} ${e.hp}♥</span>`).join('')}</div>${s.guards[id]?`<small>🛡 ${s.guards[id]}</small>`:''}</div>`;
  }).join('')}${s.built?'<div class="camp-miniatures" role="img" aria-label="Três tendas construídas, representadas por marcadores removíveis"><span>⛺</span><span>⛺</span><span>⛺</span></div>':''}</div></div><div class="map-note"><b>N1 e N2 ficam na areia.</b> A1 é a clareira da base; as tendas só aparecem após a instalação. P3 integra a planície entre praia, base e bosque. As conexões douradas correspondem às opções de Mover.</div></section>`;
}
