const {test}=require('node:test'),assert=require('node:assert/strict'),D=require('../cooperativo/defesa.js');
const ids=['aquiles','ajax','odisseu'];
const setup=()=>D.newGame({heroes:ids,levels:Object.fromEntries(ids.map(id=>[id,2]))});
function act(s,id,a,t){const r=D.act(s,id,a,t);assert.ok(r.ok,r.error);assert.ok(D.validSave(r.state));return r.state;}
test('defense has independent saves, armed heroes and named commanders on schedule',()=>{let s=setup();assert.ok(D.validSave(s));assert.equal(s.weaponStock,0);assert.ok(s.heroes.every(h=>h.weapon));s=D.trojanTurn(s);s=D.trojanTurn(s);assert.equal(s.enemies.filter(e=>e.type==='heitor').length,1);s=D.trojanTurn(s);assert.equal(s.enemies.filter(e=>e.type==='paris').length,1);assert.ok(D.validSave(s));assert.equal(require('../cooperativo/muralhas.js').validSave(s),false);});
test('camp can be invaded, area shields absorb sabotage, repairs spend action and food',()=>{let s=setup();s.heroes.forEach(h=>h.zone='N1');s.enemies=[D.TROOPS.create('e1','A1','lanceiro')];s.guards.A1=1;s=D.trojanTurn(s);assert.equal(s.campDamage,0);s=D.trojanTurn(s);assert.equal(s.campDamage,1);s.enemies=[];s.heroes[0].zone='A1';s=act(s,'aquiles','interact');assert.equal(s.campDamage,0);assert.equal(s.heroes[0].food,0);assert.equal(s.heroes[0].ap,1);assert.equal(D.act(s,'aquiles','interact').ok,false);});
test('defense requires six responses, a defender and a clear camp; timeout and five damages lose',()=>{let s=setup();s.defended=5;s.round=6;s.enemies=[];assert.equal(D.trojanTurn(s).result,'victory');s=setup();s.campDamage=4;s.heroes.forEach(h=>h.zone='N1');s.enemies=[D.TROOPS.create('e1','A1','guarda')];assert.equal(D.trojanTurn(s).result,'defeat');s=setup();s.round=8;s.heroes.forEach(h=>h.zone='N1');s.enemies=[];assert.equal(D.trojanTurn(s).result,'defeat');});
test('Paris attacks from two connected areas and armor applies to Hector',()=>{let s=setup();s.enemies=[D.TROOPS.create('e1','P3','paris')];assert.equal(D.distance('P3','A1'),2);s=D.trojanTurn(s);assert.equal(s.enemies[0].zone,'P3');assert.equal(s.heroes[0].hp,3);s=setup();s.enemies=[D.TROOPS.create('e1','A1','heitor')];s=act(s,'aquiles','card:0','e1');assert.equal(s.enemies[0].hp,6);});
test('full default N2 defense is winnable through legal actions',()=>{let s=setup();for(let round=0;round<8&&!s.result;round++){for(const id of ids){for(let i=0;i<2;i++){const h=s.heroes.find(h=>h.id===id);if(!h.hp||!h.ap||s.result)break;const d=D.HEROES.find(x=>x.id===id),e=s.enemies.filter(e=>D.distance(h.zone,e.zone)<=D.HEROES.stats(h).range).sort((a,b)=>D.distance(h.zone,a.zone)-D.distance(h.zone,b.zone))[0];if(e){const precision=d.cards.findIndex((c,n)=>c.type==='precision'&&!h.onceUsed.includes(n));if(precision>=0&&e.hp>4){s=act(s,id,'card:'+precision,e.id);continue;}const card=d.cards.findIndex((c,n)=>['attack','ranged'].includes(c.type)&&!h.used.includes(n)&&(c.type==='ranged'||e.zone===h.zone));s=act(s,id,card>=0?'card:'+card:'attack',e.id);continue;}if(h.hp<4&&h.food){s=act(s,id,'eat');continue;}const down=s.heroes.find(a=>!a.hp&&a.zone===h.zone);if(down&&h.food){s=act(s,id,'rescue',down.id);continue;}const shot=s.enemies.find(e=>D.distance(h.zone,e.zone)<=1),ranged=d.cards.findIndex((c,n)=>c.type==='ranged'&&!h.used.includes(n));if(shot&&ranged>=0){s=act(s,id,'card:'+ranged,shot.id);continue;}if(h.used.length){s=act(s,id,'rest');continue;}const guard=d.cards.findIndex(c=>c.type==='guard');if(guard>=0){s=act(s,id,'card:'+guard);continue;}break;}}if(!s.result)s=D.trojanTurn(s);assert.ok(D.validSave(s));}assert.equal(s.result,'victory',s.reason);});
