const {test}=require('node:test'),assert=require('node:assert/strict'),D=require('../cooperativo/defesa.js');
const ids=['aquiles','odisseu','agamemnon'];
const setup=()=>D.newGame({heroes:ids,levels:Object.fromEntries(ids.map(id=>[id,2]))});
function act(s,id,a,t){const r=D.act(s,id,a,t);assert.ok(r.ok,r.error);assert.ok(D.validSave(r.state));return r.state;}
function resolveExplorations(s){
 s.enemies=s.enemies.filter(e=>e.zone!=='P3');s.heroes[0].zone='P3';s=act(s,'aquiles','interact');
 s.enemies=s.enemies.filter(e=>e.zone!=='C1');s.heroes[0].zone='C1';s.heroes[0].ap=2;s=act(s,'aquiles','interact');
 return s;
}
test('defense has independent saves, armed heroes and named commanders on schedule',()=>{let s=setup();assert.ok(D.validSave(s));assert.equal(s.weaponStock,0);assert.ok(s.heroes.every(h=>h.weapon));s=D.trojanTurn(s);assert.ok(s.enemies.some(e=>e.type==='eneias'));s=D.trojanTurn(s);assert.ok(s.enemies.some(e=>e.type==='heitor'));s=D.trojanTurn(s);assert.ok(s.enemies.some(e=>e.type==='paris'));assert.ok(s.enemies.some(e=>e.type==='sarpedon'));assert.ok(D.validSave(s));assert.equal(require('../cooperativo/muralhas.js').validSave(s),false);});
test('camp can be invaded, area shields absorb sabotage, repairs spend action and food',()=>{let s=setup();s.heroes.forEach(h=>h.zone='N1');s.enemies=[D.TROOPS.create('e1','A1','lanceiro')];s.guards.A1=1;s=D.trojanTurn(s);assert.equal(s.campDamage,0);s=D.trojanTurn(s);assert.equal(s.campDamage,1);s.enemies=[];s.heroes[0].zone='A1';s=act(s,'aquiles','interact');assert.equal(s.campDamage,0);assert.equal(s.heroes[0].food,1);assert.equal(s.heroes[0].ap,1);assert.equal(D.act(s,'aquiles','interact').ok,false);});
test('two unblocked hits on A1 end the defense',()=>{let s=setup();s.heroes.forEach(h=>h.zone='N1');s.enemies=[D.TROOPS.create('e1','A1','lanceiro')];s=D.trojanTurn(s);assert.equal(s.campDamage,1);s=D.trojanTurn(s);assert.equal(s.campDamage,2);assert.equal(s.result,'defeat');});
test('P3 and C1 place the remaining territory immediately and offer evolution',()=>{let s=resolveExplorations(setup());assert.ok(s.revealedZones.includes('M3'));assert.ok(['B2','B3','B4'].every(id=>s.revealedZones.includes(id)));assert.equal(s.evolutionChoices.length,2);const chosen=s.evolutionChoices[0],level=s.heroes.find(h=>h.id===chosen).level;s=D.chooseEvolution(s,chosen).state;assert.equal(s.heroes.find(h=>h.id===chosen).level,level+1);assert.equal(s.evolutionChoices.length,0);});
test('defense requires both explorations, ten responses, a survivor and a clear camp',()=>{let s=resolveExplorations(setup());s.defended=9;s.round=10;s.enemies=[];s.heroes.forEach(h=>h.zone='N1');s.heroes[0].zone='A1';assert.equal(D.trojanTurn(s).result,'victory');s=setup();s.defended=9;s.round=10;s.enemies=[];assert.equal(D.trojanTurn(s).result,'defeat');s=setup();s.campDamage=4;s.heroes.forEach(h=>h.zone='N1');s.enemies=[D.TROOPS.create('e1','A1','guarda')];assert.equal(D.trojanTurn(s).result,'defeat');});
test('Hector retreats one area per response to M1, while Aeneas can die permanently',()=>{let s=setup();s.round=3;s.defended=2;s.heroes.forEach(h=>h.zone='P6');s.enemies=[D.TROOPS.create('h','P6','heitor')];s.enemies[0].hp=2;s.commanders.heitor='active';s=act(s,'aquiles','card:0','h');assert.equal(s.enemies[0].hp,1);assert.equal(s.enemies[0].retreating,true);assert.equal(s.commanders.heitor,'retreating');s=D.trojanTurn(s);assert.equal(s.enemies.find(e=>e.id==='h').zone,'P7');assert.equal(s.commanders.heitor,'retreating');s=D.trojanTurn(s);assert.equal(s.enemies.some(e=>e.id==='h'),false);assert.equal(s.commanders.heitor,'retreated');s.heroes[0].ap=2;s.heroes[0].used=[];s.enemies=[D.TROOPS.create('a','P6','eneias')];s.enemies[0].hp=1;s=act(s,'aquiles','card:0','a');assert.equal(s.enemies.length,0);assert.equal(s.commanders.eneias,'dead');});
test('every response before the last announces a new wave through M1 or M2',()=>{for(const heroes of [['odisseu','agamemnon','aquiles'],['odisseu','agamemnon','aquiles','ajax'],D.HEROES.map(h=>h.id)]){const s=D.newGame({players:heroes.length,heroes,owners:heroes.map((_,i)=>i+1)});assert.ok(s.enemies.every(e=>['M1','M2'].includes(e.zone)));for(let round=2;round<=10;round++){const wave=D.waves(s,round);assert.ok(wave.length>0);assert.ok(wave.every(entry=>/ em M[12]$/.test(entry)));}}});
test('campaign may continue with only one surviving hero',()=>{const campaign={commanders:{eneias:'alive',sarpedon:'dead'}},s=D.newGame({players:1,heroes:['ajax'],owners:[1],levels:{ajax:2},campaign});assert.equal(s.heroes.length,1);assert.equal(s.heroes[0].id,'ajax');assert.equal(s.commanders.sarpedon,'dead');assert.ok(D.validSave(s));});
test('Paris shoots only one area away (04/10/2026) and armor applies to Hector',()=>{let s=setup();s.enemies=[D.TROOPS.create('e1','P3','paris')];assert.equal(D.distance('P3','A1',s),2);const hp0=s.heroes.find(h=>h.id==='agamemnon').hp;s=D.trojanTurn(s);assert.equal(s.heroes.find(h=>h.id==='agamemnon').hp,hp0,'a 2 peças, Páris não alcança');s=setup();s.enemies=[D.TROOPS.create('e1','A1','heitor')];s=act(s,'aquiles','card:0','e1');assert.equal(s.enemies[0].hp,6);});
