const {test}=require('node:test'),assert=require('node:assert/strict'),H=require('../cooperativo/heroes.js');
const ids=H.map(h=>h.id);
for(const name of ['landing','muralhas']){
 const G=require('../cooperativo/'+name+'.js');
 const setup=(level=1)=>G.newGame({players:5,heroes:ids,levels:Object.fromEntries(ids.map(id=>[id,level]))});
 const hero=(s,id)=>s.heroes.find(h=>h.id===id);
 const act=(s,id,a,t)=>{const r=G.act(s,id,a,t);assert.ok(r.ok,r.error);assert.ok(G.validSave(r.state));return r.state;};
 test(name+': all evolution values and action reset',()=>{for(let n=1;n<=3;n++){let s=setup(n);assert.deepEqual(s.heroes.map(h=>h.hp),n===1?[6,6,6,6,6]:n===2?[6,6,6,6,8]:[7,7,6,8,10]);assert.deepEqual(s.heroes.map(h=>H.stats(h).attack),n===3?[4,2,2,3,2]:[n+1,2,2,2,2]);assert.deepEqual(s.heroes.map(h=>H.stats(h).armor),n===3?[0,2,0,1,0]:[0,n-1,0,0,0]);s.enemies=[];s=act(s,'menelau','card:2','aquiles');assert.equal(hero(s,'aquiles').ap,3);s=G.trojanTurn(s);assert.equal(hero(s,'aquiles').ap,2);assert.equal(hero(s,'aquiles').bonusActions,0);assert.equal(hero(s,'menelau').ap,n===1?2:3);assert.ok(G.validSave(s));}});
 test(name+': precision is exact and cannot be refreshed',()=>{let s=setup();const zone=name==='landing'?'N2':'M1';s.heroes.forEach(h=>h.zone=zone);s.enemies=[{id:'e1',zone,hp:3,armor:99}];s=act(s,'odisseu','card:0','e1');assert.equal(s.enemies[0].hp,1);assert.deepEqual(hero(s,'odisseu').onceUsed,[0]);s.enemies=[];hero(s,'odisseu').used=[1];s=act(s,'agamemnon','card:1','odisseu');assert.deepEqual(hero(s,'odisseu').used,[]);assert.equal(G.act(s,'odisseu','card:0','e1').ok,false);hero(s,'odisseu').used=[1];s=act(s,'odisseu','rest');assert.deepEqual(hero(s,'odisseu').onceUsed,[0]);});
 test(name+': piercing, stun and passive activation',()=>{let s=setup();const zone=name==='landing'?'N2':'M1';s.heroes.forEach(h=>h.zone=zone);s.enemies=[{id:'e1',zone,hp:3,armor:99}];s=act(s,'aquiles','card:0','e1');assert.equal(s.enemies.length,0);s.enemies=[{id:'e1',zone,hp:3}];s=act(s,'ajax','card:1','e1');assert.equal(s.enemies[0].stunned,true);const hp=hero(s,'ajax').hp;s=G.trojanTurn(s);assert.equal(hero(s,'ajax').hp,hp);assert.equal(s.enemies[0].stunned,false);assert.equal(G.act(s,'ajax','card:2').ok,false);});
 test(name+': basic range changes without extending Tiro Preciso',()=>{for(let n=1;n<=3;n++){let s=setup(n),h=hero(s,'odisseu');const zone=Object.keys(G.ZONES).find(z=>G.distance(h.zone,z)===2&&z!=='A1');s.enemies=[{id:'e1',zone,hp:3}];assert.equal(G.act(s,'odisseu','attack','e1').ok,n===3);assert.equal(G.act(s,'odisseu','card:1','e1').ok,false);}});
 test(name+': taunt directs movement, protects and expires',()=>{let s=setup(),zone=name==='landing'?'N2':'M1';s.heroes.forEach(h=>h.zone=zone);s.enemies=[{id:'e1',zone,hp:3}];s=act(s,'agamemnon','card:0');s=G.trojanTurn(s);assert.equal(hero(s,'agamemnon').hp,5);assert.equal(hero(s,'aquiles').hp,6);assert.equal(H.armor(hero(s,'agamemnon'),s),0);assert.ok(G.validSave(s));});
 test(name+': survivor only once, dodge once per round, armor and caps',()=>{let s=setup(3),a=hero(s,'ajax'),q=hero(s,'aquiles');a.hp=1;H.damage(s,a,3,()=>{});assert.equal(a.hp,1);assert.deepEqual(a.onceUsed,[2]);H.damage(s,a,3,()=>{});assert.equal(a.hp,0);H.damage(s,q,2,()=>{});assert.equal(q.hp,7);H.damage(s,q,2,()=>{});assert.equal(q.hp,5);s.round++;H.damage(s,q,2,()=>{});assert.equal(q.hp,5);H.damage(s,q,3,()=>{});assert.equal(q.hp,2);s.enemies=[];s=act(s,'aquiles','card:2');assert.equal(hero(s,'aquiles').hp,5);assert.ok(G.validSave(s));});
 test(name+': save rejects invalid levels, unique-use state and action totals',()=>{for(const change of [h=>h.level=4,h=>h.onceUsed=[0],h=>h.ap=3,h=>h.used=[2,2]]){const s=setup();change(s.heroes[0]);assert.equal(G.validSave(s),false);}});
}
