const {test}=require('node:test'),assert=require('node:assert/strict'),H=require('../cooperativo/heroes.js');
const ids=H.map(h=>h.id);
for(const name of ['landing','muralhas']){
 const G=require('../cooperativo/'+name+'.js');
 const setup=(level=1)=>{let s=G.newGame({players:5,heroes:ids,levels:Object.fromEntries(ids.map(id=>[id,level]))});if(name==='landing'){for(const h of s.heroes)for(let i=0;i<2;i++)s=G.allocateFood(s,h.id,1).state;s=G.finishFoodSetup(s).state;s.revealed=Object.keys(G.ZONES);s.visited=[...s.revealed];}return s;};
 const hero=(s,id)=>s.heroes.find(h=>h.id===id);
 const act=(s,id,a,t)=>{const r=G.act(s,id,a,t);assert.ok(r.ok,r.error);assert.ok(G.validSave(r.state));return r.state;};
 test(name+': all evolution values and action reset',()=>{for(let n=1;n<=3;n++){let s=setup(n);assert.deepEqual(s.heroes.map(h=>h.hp),n===1?[6,6,6,6,6]:n===2?[6,6,6,6,8]:[7,7,6,8,10]);assert.deepEqual(s.heroes.map(h=>H.stats(h).attack),n===3?[4,2,2,2,2]:[n+1,2,2,2,2]);assert.deepEqual(s.heroes.map(h=>H.stats(h).armor),n===3?[0,2,0,0,0]:[0,n-1,0,0,0]);s.enemies=[];s=act(s,'menelau','card:2','aquiles');assert.equal(hero(s,'aquiles').ap,3);s=G.trojanTurn(s);assert.equal(hero(s,'aquiles').ap,2);assert.equal(hero(s,'aquiles').bonusActions,0);assert.equal(hero(s,'menelau').ap,n===1?2:3);assert.ok(G.validSave(s));}});
 test(name+': precision is exact and cannot be refreshed',()=>{let s=setup();const zone=name==='landing'?'N2':'M1';s.heroes.forEach(h=>h.zone=zone);s.enemies=[{id:'e1',zone,hp:3,armor:99}];s=act(s,'odisseu','card:0','e1');assert.equal(s.enemies[0].hp,1);assert.deepEqual(hero(s,'odisseu').onceUsed,[0]);s.enemies=[];hero(s,'odisseu').used=[1];s=act(s,'agamemnon','card:1','odisseu');assert.deepEqual(hero(s,'odisseu').used,[]);assert.equal(G.act(s,'odisseu','card:0','e1').ok,false);hero(s,'odisseu').used=[1];s=act(s,'odisseu','rest');assert.deepEqual(hero(s,'odisseu').onceUsed,[0]);});
 test(name+': piercing, stun and passive activation',()=>{let s=setup();const zone=name==='landing'?'N2':'M1';s.heroes.forEach(h=>h.zone=zone);s.enemies=[{id:'e1',zone,hp:3,armor:99}];s=act(s,'aquiles','card:0','e1');assert.equal(s.enemies.length,0);s.enemies=[{id:'e1',zone,hp:3}];s=act(s,'ajax','card:1','e1');assert.equal(s.enemies[0].stunned,true);const hp=hero(s,'ajax').hp;s=G.trojanTurn(s);assert.equal(hero(s,'ajax').hp,hp);assert.equal(s.enemies[0].stunned,false);assert.equal(G.act(s,'ajax','card:2').ok,false);});
 test(name+': Disparo Duplo reaches one neighboring area and strikes two armored enemies',()=>{for(let n=1;n<=3;n++){let s=setup(n),h=hero(s,'odisseu');const neighbor=G.ZONES[h.zone].links.find(z=>z!=='A1');s.enemies=[{id:'e1',zone:neighbor,hp:4,armor:9},{id:'e2',zone:neighbor,hp:4,armor:9}];const shot=G.act(s,'odisseu','card:1','e1,e2');assert.ok(shot.ok,shot.error);assert.deepEqual(shot.state.enemies.map(e=>e.hp),[2,2]);const far=Object.keys(G.ZONES).find(z=>G.distance(h.zone,z)===2);s.enemies=[{id:'e1',zone:far,hp:4,armor:9},{id:'e2',zone:far,hp:4,armor:9}];assert.equal(G.act(s,'odisseu','card:1','e1,e2').ok,false);}});
 test(name+': taunt directs movement, protects and expires',()=>{let s=setup(),zone=name==='landing'?'N2':'M1';s.heroes.forEach(h=>h.zone=zone);s.enemies=[{id:'e1',zone,hp:3}];s=act(s,'agamemnon','card:0');s=G.trojanTurn(s);assert.equal(hero(s,'agamemnon').hp,5);assert.equal(hero(s,'aquiles').hp,6);assert.equal(H.armor(hero(s,'agamemnon'),s),0);assert.ok(G.validSave(s));});
 test(name+': intimidation forces retreat and prevents the next attack',()=>{let s=setup(),zone=name==='landing'?'N2':'P4';s.heroes.forEach(h=>h.zone=zone);s.enemies=[{id:'e1',zone,hp:3,attack:3}];s=act(s,'agamemnon','card:2','e1');const enemy=s.enemies[0];assert.notEqual(enemy.zone,zone);assert.equal(enemy.intimidated,true);hero(s,'aquiles').zone=enemy.zone;const hp=hero(s,'aquiles').hp;s=G.trojanTurn(s);assert.equal(hero(s,'aquiles').hp,hp);assert.equal(s.enemies[0].intimidated,false);assert.ok(G.validSave(s));});
 test(name+': survivor only once, dodge once per round, armor and full recovery',()=>{let s=setup(3),a=hero(s,'ajax'),q=hero(s,'aquiles');a.hp=1;H.damage(s,a,3,()=>{});assert.equal(a.hp,1);assert.deepEqual(a.onceUsed,[2]);H.damage(s,a,3,()=>{});assert.equal(a.hp,0);H.damage(s,q,2,()=>{});assert.equal(q.hp,7);H.damage(s,q,2,()=>{});assert.equal(q.hp,5);s.round++;H.damage(s,q,2,()=>{});assert.equal(q.hp,5);H.damage(s,q,3,()=>{});assert.equal(q.hp,2);s.enemies=[];s=act(s,'aquiles','card:2');assert.equal(hero(s,'aquiles').hp,H.stats(hero(s,'aquiles')).maxHp);assert.ok(G.validSave(s));});
 test(name+': Veterano de Esparta rescues a fallen ally once per round, after Survivor',()=>{let s=setup(3);const m=hero(s,'menelau'),q=hero(s,'aquiles'),o=hero(s,'odisseu'),a=hero(s,'ajax'),dist=(x,y)=>G.distance(x,y,s),log=()=>{};const near=G.ZONES[m.zone].links[0];q.zone=near;o.zone=near;a.zone=near;H.damage(s,a,99,log,{distance:dist});assert.equal(a.hp,1);assert.equal(a.zone,near);assert.equal(m.rescueRound??0,0);H.damage(s,q,99,log,{distance:dist});assert.equal(q.hp,1);assert.equal(q.zone,m.zone);assert.equal(m.rescueRound,s.round);H.damage(s,o,99,log,{distance:dist});assert.equal(o.hp,0);assert.equal(o.zone,near);assert.ok(G.validSave(s));s.round++;H.damage(s,q,99,log,{distance:dist});assert.equal(q.hp,1);const far=Object.keys(G.ZONES).find(z=>dist(m.zone,z)===2);o.hp=6;o.zone=far;s.round++;H.damage(s,o,99,log,{distance:dist});assert.equal(o.hp,0);let low=setup(2);const lq=hero(low,'aquiles');H.damage(low,lq,99,log,{distance:(x,y)=>G.distance(x,y,low)});assert.equal(lq.hp,0);});
 test(name+': save rejects invalid levels, unique-use state and action totals',()=>{for(const change of [h=>h.level=4,h=>h.onceUsed=[0],h=>h.ap=3,h=>h.used=[2,2]]){const s=setup();change(s.heroes[0]);assert.equal(G.validSave(s),false);}});
}
