const {test}=require('node:test'),assert=require('node:assert/strict'),G=require('../cooperativo/muralhas.js');
function act(s,id,a,t){const r=G.act(s,id,a,t);assert.equal(r.ok,true,r.error);assert.ok(G.validSave(r.state));return r.state;}
test('guard blocks the gate attack; Paris answers first and Hector arrives next round',()=>{let s=G.newGame(),o=s.heroes.find(h=>h.id==='odisseu');o.zone='M1';assert.equal(G.act(s,'odisseu','attack','gate').ok,false);for(let n=0;n<4;n++){o=s.heroes.find(h=>h.id==='odisseu');o.ap=2;s=act(s,'odisseu','attack','e1');}assert.equal(s.enemies.some(e=>e.zone==='M1'&&e.type==='guarda'),false);s.heroes.find(h=>h.id==='odisseu').ap=2;s=act(s,'odisseu','attack','gate');assert.equal(s.gateAssaulted,true);assert.equal(s.retreatDeadline,7);assert.equal(s.enemies.filter(e=>e.type==='lanceiro').length,2);assert.equal(s.enemies.some(e=>e.type==='heitor'),false);assert.ok(s.enemies.some(e=>e.type==='paris'));s=G.trojanTurn(s);assert.ok(s.enemies.some(e=>e.type==='heitor'));});
test('only melee attacks trigger retaliation, rounded down',()=>{let s=G.newGame();s.enemies=[G.TROOPS.create('e1','M1','lanceiro')];s.heroes.find(h=>h.id==='aquiles').zone='M1';s=act(s,'aquiles','attack','e1');assert.equal(s.heroes.find(h=>h.id==='aquiles').hp,5);s=G.newGame({levels:{odisseu:2}});s.heroes.find(h=>h.id==='odisseu').zone='M4';s=act(s,'odisseu','attack','e1');assert.equal(s.heroes.find(h=>h.id==='odisseu').hp,6);});
test('evolution exploration is single-use and offers only present heroes',()=>{let s=G.newGame(),o=s.heroes.find(h=>h.id==='odisseu');o.zone='P2';s=act(s,'odisseu','interact');assert.equal(s.explorations.P2.resolved,true);assert.equal(s.evolutionChoices.length,2);assert.ok(s.evolutionChoices.every(id=>s.heroes.some(h=>h.id===id)));assert.equal(G.act(s,'odisseu','interact').ok,false);const chosen=s.evolutionChoices[0],r=G.chooseEvolution(s,chosen);assert.ok(r.ok);assert.equal(r.state.heroes.find(h=>h.id===chosen).level,2);assert.deepEqual(r.state.evolutionChoices,[]);assert.ok(G.validSave(r.state));});
test('retreat succeeds after the gate assault with every survivor in A1',()=>{let s=G.newGame();s.enemies=[];s.heroes.find(h=>h.id==='odisseu').zone='M1';s=act(s,'odisseu','attack','gate');assert.equal(G.act(s,'agamemnon','interact').ok,false);s.enemies=[];s.heroes.forEach(h=>{h.zone='A1';h.ap=2});s.heroes.find(h=>h.id==='aquiles').hp=0;s.heroes.find(h=>h.id==='aquiles').ap=0;s=act(s,'agamemnon','interact');assert.equal(s.result,'victory');});
test('safe base excludes enemy movement and mission timeout ends attempt',()=>{let s=G.newGame();s.enemies[0].zone='P3';s=G.trojanTurn(s);assert.equal(s.enemies[0].zone,'P3');assert.ok(s.heroes.every(h=>h.hp===6));s=G.newGame();s.round=14;assert.equal(G.trojanTurn(s).result,'defeat');});
test('mission two starts with sixteen pieces and can reveal the complete final board',()=>{const L=require('../cooperativo/landing.js'),s=G.newGame();assert.equal(s.revealedZones.length,16);for(const id of Object.keys(L.ZONES).filter(id=>id!=='C1'))assert.ok(s.revealedZones.includes(id));assert.equal(Object.keys(G.ZONES).length,26);for(const [id,z]of Object.entries(G.ZONES))for(const n of z.links)assert.ok(G.ZONES[n].links.includes(id),id+'→'+n);});
test('ordinary retreat takes half of the weakest enemy attack rounded down and ignores armor',()=>{let s=G.newGame({heroes:['odisseu','agamemnon','ajax'],levels:{ajax:3}}),h=s.heroes.find(h=>h.id==='ajax');h.zone='P3';s.enemies=[G.TROOPS.create('x','P3','lanceiro')];const r=G.act(s,'ajax','move','P1');assert.ok(r.ok);assert.equal(r.state.heroes.find(h=>h.id==='ajax').hp,6);assert.equal(r.state.heroes.find(h=>h.id==='ajax').zone,'P1');});
test('revealed B5 reaches M1 and scheduled units enter M4 without sentry status',()=>{const s=G.newGame();assert.ok(G.ZONES.B5.links.includes('M1'));assert.ok(G.ZONES.M1.links.includes('B5'));assert.deepEqual(G.waves(s,2),['M4']);assert.deepEqual(G.waves(s,5),['M4']);let next=G.trojanTurn(s);const scout=next.enemies.find(e=>e.type==='explorador');assert.equal(scout.zone,'M4');assert.equal(scout.sentry,undefined);});
test('an allied rebound does not spend an active area shield',()=>{let s=G.newGame({heroes:['odisseu','agamemnon','ajax']}),ajax=s.heroes.find(h=>h.id==='ajax');s.heroes.forEach(h=>h.zone='M1');s.enemies=[G.TROOPS.create('e1','M1','lanceiro')];s.guards.M1=3;s=act(s,'agamemnon','attack','e1');assert.equal(s.guards.M1,3);assert.equal(ajax.hp,6);});
