const {test}=require('node:test'),assert=require('node:assert/strict'),G=require('../cooperativo/muralhas.js');
const setup=()=>{const s=G.newGame();s.heroes[0].zone='M1';return s;};
function act(s,id,a,t){const r=G.act(s,id,a,t);assert.equal(r.ok,true,r.error);assert.ok(G.validSave(r.state));return r.state;}
test('surviving troops retaliate once, lethal attacks do not; no mutation of input',()=>{let s=setup();const before=JSON.stringify(s);let n=act(s,'aquiles','attack','e1');assert.equal(n.enemies[0].hp,1);assert.equal(n.heroes[0].hp,5);assert.equal(n.heroes[0].ap,1);assert.equal(JSON.stringify(s),before);n=act(n,'aquiles','attack','e1');assert.equal(n.enemies.length,0);assert.equal(n.heroes[0].hp,5);});
test('ranged and charge attacks apply retaliation; guard absorbs it',()=>{let s=G.newGame();s.heroes[2].zone='M4';s=act(s,'odisseu','card:1','e1');assert.equal(s.heroes[2].hp,5);s=setup();s.heroes[0].zone='M4';s.guards.M1=1;s=act(s,'aquiles','card:1','e1');assert.equal(s.heroes[0].hp,6);assert.equal(s.guards.M1,0);assert.equal(s.heroes[0].zone,'M1');});
test('retaliation can down attacker and finish mission without negative actions',()=>{let s=setup();s.heroes.forEach(h=>{h.hp=0;h.ap=0});s.heroes[0].hp=1;s.heroes[0].ap=1;s=act(s,'aquiles','attack','e1');assert.equal(s.heroes[0].ap,0);assert.equal(s.result,'defeat');});
test('trojan attacks trigger survivor retaliation, never fallen-hero retaliation',()=>{let s=setup();s=G.trojanTurn(s);assert.equal(s.heroes[0].hp,4);assert.equal(s.enemies[0].hp,2);s=setup();s.heroes[0].hp=1;s=G.trojanTurn(s);assert.equal(s.enemies[0].hp,3);assert.equal(s.heroes[0].hp,0);});
test('killing enemy by retaliation does not skip next troop activation',()=>{let s=setup();s.enemies=[{id:'e1',hp:1,zone:'M1'},{id:'e2',hp:3,zone:'M1'}];s.nextEnemy=3;s=G.trojanTurn(s);assert.equal(s.enemies.length,1);assert.equal(s.enemies[0].id,'e2');assert.equal(s.enemies[0].hp,2);assert.equal(s.heroes[0].hp,2);assert.ok(G.validSave(s));});
test('food collection has capacity, finite stock and costs an action',()=>{let s=G.newGame();s=act(s,'aquiles','gather');s=act(s,'aquiles','gather');assert.equal(s.heroes[0].food,3);assert.equal(s.foodSites.A1,4);s.heroes[0].ap=2;assert.equal(G.act(s,'aquiles','gather').ok,false);s.heroes[1].zone='B3';s=act(s,'ajax','gather');s=act(s,'ajax','gather');assert.equal(s.foodSites.B3,0);s.heroes[2].zone='B3';assert.equal(G.act(s,'odisseu','gather').ok,false);assert.ok(G.validSave(JSON.parse(JSON.stringify(s))));});
test('eating consumes one ration, caps healing and cannot work during combat',()=>{let s=G.newGame();s.heroes[0].hp=5;s=act(s,'aquiles','eat');assert.equal(s.heroes[0].hp,6);assert.equal(s.heroes[0].food,0);assert.equal(s.foodSpent,1);s.heroes[0].hp=3;assert.equal(G.act(s,'aquiles','eat').ok,false);s=setup();s.heroes[0].hp=3;assert.equal(G.act(s,'aquiles','eat').ok,false);assert.equal(G.act(s,'aquiles','gather').ok,false);});
test('preparing cards never heals and medical abilities cannot bypass food',()=>{let s=G.newGame();s.heroes[0].hp=2;s.heroes[0].used=[0];s=act(s,'aquiles','rest');assert.equal(s.heroes[0].hp,2);assert.equal(s.heroes[0].food,1);s=act(s,'aquiles','card:2');assert.equal(s.heroes[0].hp,5);assert.equal(s.heroes[0].food,0);s.heroes[0].ap=2;s.heroes[0].used=[];assert.equal(G.act(s,'aquiles','card:2').ok,false);});
test('rescue and ally cure consume the acting heros food; sharing conserves food',()=>{let s=G.newGame({heroes:['aquiles','menelau','odisseu']});s.heroes[0].hp=0;s.heroes[0].ap=0;s=act(s,'menelau','rescue','aquiles');assert.equal(s.heroes[0].hp,2);assert.equal(s.heroes[0].ap,0);assert.equal(s.heroes[1].food,0);assert.equal(G.act(s,'menelau','card:0','aquiles').ok,false);s=act(s,'odisseu','share','menelau');assert.equal(s.heroes[1].food,1);s=act(s,'menelau','card:0','aquiles');assert.equal(s.heroes[0].hp,4);assert.equal(s.foodSpent,2);});
test('save rejects fabricated food, obsolete map and unsupported zones',()=>{for(const change of [s=>s.heroes[0].food++,s=>s.foodSites.B1++,s=>s.version=2,s=>s.heroes[0].zone='N1']){let s=G.newGame();change(s);assert.equal(G.validSave(s),false);}});
test('approved map has reciprocal paths and reachable objectives',()=>{assert.equal(Object.keys(G.ZONES).length,21);assert.ok(G.ZONES.C1);assert.ok(G.ZONES.A2&&G.ZONES.P5);for(const [id,z]of Object.entries(G.ZONES)){assert.ok(Number.isFinite(G.distance('A1',id)));for(const n of z.links)assert.ok(G.ZONES[n].links.includes(id));}});
